<a href="https://colab.research.google.com/github/wwchiam/myPythonPractice/blob/main/Day72_Advanced_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Summary - Source. Udemy 100-days-of-code

*  Use .head(), .tail(), .shape and .columns to explore your DataFrame and find out the number of rows and columns as well as the column names.

* Look for NaN (not a number) values with .findna() and consider using .dropna() to clean up your DataFrame.

* You can access entire columns of a DataFrame using the square bracket notation: df['column name'] or df[['column name 1', 'column name 2', 'column name 3']]

* You can access individual cells in a DataFrame by chaining square brackets df['column name'][index] or using df['column name'].loc[index]

* The largest and smallest values, as well as their positions, can be found with methods like .max(), .min(), .idxmax() and .idxmin()

* You can sort the DataFrame with .sort_values() and add new columns with .insert()

* To create an Excel Style Pivot Table by grouping entries that belong to a particular category use the .groupby() method

In [1]:
import pandas as pd

df=pd.read_csv("salaries_by_college_major.csv")

In [3]:
df.head()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
0,Accounting,46000.0,77100.0,42200.0,152000.0,Business
1,Aerospace Engineering,57700.0,101000.0,64300.0,161000.0,STEM
2,Agriculture,42600.0,71900.0,36300.0,150000.0,Business
3,Anthropology,36800.0,61500.0,33800.0,138000.0,HASS
4,Architecture,41600.0,76800.0,50600.0,136000.0,Business

# Section 1: Table exploration + Cleaning

In [5]:
df.shape

(51, 6)

In [7]:
df.columns

Index(['Undergraduate Major', 'Starting Median Salary',
       'Mid-Career Median Salary', 'Mid-Career 10th Percentile Salary',
       'Mid-Career 90th Percentile Salary', 'Group'],
      dtype='object')

Look for NaN (Not A Number) values in our dataframe. NAN values are blank cells or cells that contain strings instead of numbers.

In [10]:
df.isna()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
0,False,False,False,False,False,False
1,False,False,False,False,False,False
2,False,False,False,False,False,False
3,False,False,False,False,False,False
4,False,False,False,False,False,False
5,False,False,False,False,False,False
6,False,False,False,False,False,False
7,False,False,False,False,False,False
8,False,False,False,False,False,False
9,False,False,False,False,False,False
10,False,False,False,False,False,False
11,False,False,False,False,False,False
12,False,False,False,False,False,False
13,False,False,False,False,False,False
14,False,False,False,False,False,False
15,False,False,False,False,False,False
16,False,False,False,False,False,False
17,False,False,False,False,False,False
18,False,False,False,False,False,False
19,False,False,False,False,False,False
20,False,False,False,False,False,False
21,False,False,False,False,False,False
22,False,False,False,False,False,False
23,False,False,False,False,False,False
24,False,False,False,False,False,False
25,False,False,False,False,False,False
26,False,False,False,False,False,False
27,False,False,False,False,False,False
28,False,False,False,False,False,False
29,False,False,False,False,False,False
30,False,False,False,False,False,False
31,False,False,False,False,False,False
32,False,False,False,False,False,False
33,False,False,False,False,False,False
34,False,False,False,False,False,False
35,False,False,False,False,False,False
36,False,False,False,False,False,False
37,False,False,False,False,False,False
38,False,False,False,False,False,False
39,False,False,False,False,False,False
40,False,False,False,False,False,False
41,False,False,False,False,False,False
42,False,False,False,False,False,False
43,False,False,False,False,False,False
44,False,False,False,False,False,False
45,False,False,False,False,False,False
46,False,False,False,False,False,False
47,False,False,False,False,False,False
48,False,False,False,False,False,False
49,False,False,False,False,False,False
50,False,True,True,True,True,True

In [12]:
df.tail()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
46,Psychology,35900.0,60400.0,31600.0,127000.0,HASS
47,Religion,34100.0,52000.0,29700.0,96400.0,HASS
48,Sociology,36500.0,58200.0,30700.0,118000.0,HASS
49,Spanish,34000.0,53100.0,31000.0,96400.0,HASS
50,Source: PayScale Inc.,NaN,NaN,NaN,NaN,NaN

In [13]:
clean_df=df.dropna()

In [14]:
clean_df.tail()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
45,Political Science,40800.0,78200.0,41200.0,168000.0,HASS
46,Psychology,35900.0,60400.0,31600.0,127000.0,HASS
47,Religion,34100.0,52000.0,29700.0,96400.0,HASS
48,Sociology,36500.0,58200.0,30700.0,118000.0,HASS
49,Spanish,34000.0,53100.0,31000.0,96400.0,HASS

# Section 2: Simple Exploration

In [16]:
clean_df['Starting Median Salary']

0     46000.0
1     57700.0
2     42600.0
3     36800.0
4     41600.0
5     35800.0
6     38800.0
7     43000.0
8     63200.0
9     42600.0
10    53900.0
11    38100.0
12    61400.0
13    55900.0
14    53700.0
15    35000.0
16    35900.0
17    50100.0
18    34900.0
19    60900.0
20    38000.0
21    37900.0
22    47900.0
23    39100.0
24    41200.0
25    43500.0
26    35700.0
27    38800.0
28    39200.0
29    37800.0
30    57700.0
31    49100.0
32    36100.0
33    40900.0
34    35600.0
35    49200.0
36    40800.0
37    45400.0
38    57900.0
39    35900.0
40    54200.0
41    39900.0
42    39900.0
43    74300.0
44    50300.0
45    40800.0
46    35900.0
47    34100.0
48    36500.0
49    34000.0
Name: Starting Median Salary, dtype: float64

In [17]:
clean_df['Starting Median Salary'].max()

74300.0

In [19]:
clean_df['Starting Median Salary'].idxmax()

np.int64(43)

In [21]:
clean_df['Starting Median Salary'].loc[43]

np.float64(74300.0)

In [22]:
clean_df['Undergraduate Major'].loc[43]

'Physician Assistant'

In [23]:
clean_df.loc[43]

Undergraduate Major                  Physician Assistant
Starting Median Salary                           74300.0
Mid-Career Median Salary                         91700.0
Mid-Career 10th Percentile Salary                66400.0
Mid-Career 90th Percentile Salary               124000.0
Group                                               STEM
Name: 43, dtype: object

# Practice

What college major has the highest mid-career salary? How much do graduates with this major earn? (Mid-career is defined as having 10+ years of experience).

In [24]:
clean_df["Mid-Career Median Salary"].idxmax()

np.int64(8)

In [25]:
clean_df.loc[8]

Undergraduate Major                  Chemical Engineering
Starting Median Salary                            63200.0
Mid-Career Median Salary                         107000.0
Mid-Career 10th Percentile Salary                 71900.0
Mid-Career 90th Percentile Salary                194000.0
Group                                                STEM
Name: 8, dtype: object

In [34]:
print(clean_df["Mid-Career Median Salary"].max())
print(f"Index for the max mid career salary: {clean_df['Mid-Career Median Salary'].idxmax()}")
clean_df['Undergraduate Major'][8]

107000.0
Index for the max mid career salary: 8

'Chemical Engineering'

Which college major has the lowest starting salary and how much do graduates earn after university?

In [26]:
clean_df["Starting Median Salary"].idxmin()

np.int64(49)

In [30]:
clean_df.loc[49]

Undergraduate Major                  Spanish
Starting Median Salary               34000.0
Mid-Career Median Salary             53100.0
Mid-Career 10th Percentile Salary    31000.0
Mid-Career 90th Percentile Salary    96400.0
Group                                   HASS
Name: 49, dtype: object

In [35]:
print(clean_df['Starting Median Salary'].min())
clean_df['Undergraduate Major'].loc[clean_df['Starting Median Salary'].idxmin()]

34000.0

'Spanish'

Which college major has the lowest mid-career salary and how much can people expect to earn with this degree?

In [31]:
clean_df["Mid-Career Median Salary"].idxmin()

np.int64(18)

In [32]:
clean_df.loc[18]

Undergraduate Major                  Education
Starting Median Salary                 34900.0
Mid-Career Median Salary               52000.0
Mid-Career 10th Percentile Salary      29300.0
Mid-Career 90th Percentile Salary     102000.0
Group                                     HASS
Name: 18, dtype: object

# Section 3: Sorting / Add Columns

In [37]:
#clean_df['Mid-Career 90th Percentile Salary'] - clean_df['Mid-Career 10th Percentile Salary']
clean_df['Mid-Career 90th Percentile Salary'].subtract(clean_df['Mid-Career 10th Percentile Salary'])

0     109800.0
1      96700.0
2     113700.0
3     104200.0
4      85400.0
5      96200.0
6      98100.0
7     108200.0
8     122100.0
9     102700.0
10     84600.0
11    105500.0
12     95900.0
13     98000.0
14    114700.0
15     74800.0
16    116300.0
17    159400.0
18     72700.0
19     98700.0
20     99600.0
21    102100.0
22    147800.0
23     70000.0
24     92000.0
25    111000.0
26     76000.0
27     66400.0
28    112000.0
29     88500.0
30    115900.0
31     84500.0
32     71300.0
33    118800.0
34    106600.0
35    100700.0
36    132900.0
37    137800.0
38     99300.0
39    107300.0
40     50700.0
41     65300.0
42    132500.0
43     57600.0
44    122000.0
45    126800.0
46     95400.0
47     66700.0
48     87300.0
49     65400.0
dtype: float64

In [38]:
spread_col = clean_df['Mid-Career 90th Percentile Salary'] - clean_df['Mid-Career 10th Percentile Salary']
clean_df.insert(1, 'Spread', spread_col)
clean_df.head()

,Undergraduate Major,Spread,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
0,Accounting,109800.0,46000.0,77100.0,42200.0,152000.0,Business
1,Aerospace Engineering,96700.0,57700.0,101000.0,64300.0,161000.0,STEM
2,Agriculture,113700.0,42600.0,71900.0,36300.0,150000.0,Business
3,Anthropology,104200.0,36800.0,61500.0,33800.0,138000.0,HASS
4,Architecture,85400.0,41600.0,76800.0,50600.0,136000.0,Business

In [39]:
low_risk = clean_df.sort_values('Spread')
low_risk[['Undergraduate Major', 'Spread']].head()

           Undergraduate Major   Spread
40                     Nursing  50700.0
43         Physician Assistant  57600.0
41                   Nutrition  65300.0
49                     Spanish  65400.0
27  Health Care Administration  66400.0

# Practice

Using the .sort_values() method, can you find the degrees with the highest potential? Find the top 5 degrees with the highest values in the 90th percentile.

Also, find the degrees with the greatest spread in salaries. Which majors have the largest difference between high and low earners after graduation.

In [40]:
high_potential=clean_df.sort_values('Mid-Career 90th Percentile Salary', ascending=False)
high_potential[['Undergraduate Major', 'Mid-Career 90th Percentile Salary']].head()

     Undergraduate Major  Mid-Career 90th Percentile Salary
17             Economics                           210000.0
22               Finance                           195000.0
8   Chemical Engineering                           194000.0
37                  Math                           183000.0
44               Physics                           178000.0

In [52]:
difference_col = clean_df['Mid-Career 90th Percentile Salary'] - clean_df['Mid-Career 10th Percentile Salary']
clean_df.insert(5,"Difference",difference_col)

In [53]:
clean_df.head()

,Undergraduate Major,Spread,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Difference,Mid-Career 90th Percentile Salary,Group
0,Accounting,109800.0,46000.0,77100.0,42200.0,109800.0,152000.0,Business
1,Aerospace Engineering,96700.0,57700.0,101000.0,64300.0,96700.0,161000.0,STEM
2,Agriculture,113700.0,42600.0,71900.0,36300.0,113700.0,150000.0,Business
3,Anthropology,104200.0,36800.0,61500.0,33800.0,104200.0,138000.0,HASS
4,Architecture,85400.0,41600.0,76800.0,50600.0,85400.0,136000.0,Business

In [58]:
clean_df.sort_values('Difference', ascending=False).head()
clean_df[["Undergraduate Major","Starting Median Salary","Mid-Career 10th Percentile Salary","Mid-Career 90th Percentile Salary"]].head()

,Undergraduate Major,Starting Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary
0,Accounting,46000.0,42200.0,152000.0
1,Aerospace Engineering,57700.0,64300.0,161000.0
2,Agriculture,42600.0,36300.0,150000.0
3,Anthropology,36800.0,33800.0,138000.0
4,Architecture,41600.0,50600.0,136000.0

# Section 4: Group By

In [61]:
clean_df.groupby("Group").count()

,Undergraduate Major,Spread,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Difference,Mid-Career 90th Percentile Salary
Group,,,,,,,
Business,12,12,12,12,12,12,12
HASS,22,22,22,22,22,22,22
STEM,16,16,16,16,16,16,16

In [69]:
clean_df.groupby("Group").mean(numeric_only=True)

,Spread,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Difference,Mid-Career 90th Percentile Salary
Group,,,,,,
Business,103958.333333,44633.333333,75083.333333,43566.666667,103958.333333,147525.000000
HASS,95218.181818,37186.363636,62968.181818,34145.454545,95218.181818,129363.636364
STEM,101600.000000,53862.500000,90812.500000,56025.000000,101600.000000,157625.000000

In [70]:
pd.options.display.float_format = '{:,.2f}'.format

In [71]:
clean_df.groupby("Group").mean(numeric_only=True)

,Spread,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Difference,Mid-Career 90th Percentile Salary
Group,,,,,,
Business,"103,958.33","44,633.33","75,083.33","43,566.67","103,958.33","147,525.00"
HASS,"95,218.18","37,186.36","62,968.18","34,145.45","95,218.18","129,363.64"
STEM,"101,600.00","53,862.50","90,812.50","56,025.00","101,600.00","157,625.00"